### ISSUE TITLE
EnumFieldSerializerMixin always serializes lowercase value as uppercase

### ISSUE THREAD

**Issue by estianross** [seebass/drf-enum-field#11]
EnumFieldSerializerMixin always serializes lowercase value as uppercase. This breaks import  for serialized data.

DEFAULT = 'default' is always serialized as DEFAULT. This breaks import on serialized data.

**Comment by johncpang** [comment]
I think the correct statement should be: `EnumFieldSerializerMixin` use the `.name` (i.e. DEFAULT) instead of `.value` (i.e. 'default').  

To verify this behavior, create an enum with different name vs value.  For example: `NA = 'n/a'`.  It will be "n/a" in database, and display as "NA" when serialized.

If you want the representation of enum match with the value stored in database, both name and value must be exactly the same:

```python
from enumfields import Enum

class Gender(Enum):
    na = 'na'
    male = 'male'
    female = 'female'

    class Labels:
        na = _('n/a')
        male = _('Male')
        female = _('Female')
```

**Comment by Archelyst** [comment]
This is now fixed
